# Only build specific branches... Secure version costs a lot of money :/
branches:
#  only:
#    - master

# We are using javascript tests
language: node_js

# Tell me whats going on...
notifications:
  email: true

# Allow admin rights
sudo: true

# What version to run
node_js:
  - '0.10'

# Install dependencies for the build
before_script:
  - 'npm install -g grunt-cli'

# Setting this overrides "npm test" which is the default
script:
  - 'grunt production'

# Anything after?
after_script:
